### ISSUE TITLE
Analyze cloned repos

### ISSUE THREAD

**Issue by nniiicc** [PugetSoundClinic-PIT/ProjectTracking#142]

**Comment by nniiicc** [comment]
Metrics to calculate or get
- Burstiness (from Chaoss)
- Last substantive commit (for sustainability categorization) 
- Bus factor (from Ecosystems)

**Comment by evamaxfield** [comment]
Closing for now as I have burstiness + Last substantive commit and I can easily implement bus factor using the definition from CHAOSS (or ecosystems).

There are a few more metrics picked out from CHAOSS we are interested in but I will open a new issue for those when I work on them next.
