### ISSUE TITLE
Start on Script to Link GitHub Repos w/ Their NSF Award Page

### ISSUE THREAD

**Issue by evamaxfield** [PugetSoundClinic-PIT/ProjectTracking#26]
Take the list of GitHub repos and write script to run each one through function to get the associated NSF Award Link.

The subset to annotate will come from the data points that have both the GitHub + the Abstract award link.

**Comment by evamaxfield** [comment]
cc @nniiicc and @lindseysschwartz just want to make sure this is correct.

**Comment by nniiicc** [comment]
Yes

**Comment by evamaxfield** [comment]
Script pushed and currently running against all 1400 repos. Will keep this issue updated.

I will also have a couple of notes to add later. We are being very generous in our linkage.
