### ISSUE TITLE
More Gig Plat Linear Regressions, Try to Add All Terms

### ISSUE THREAD

**Issue by evamaxfield** [PugetSoundClinic-PIT/ProjectTracking#28]
Work with Lindsey to come up with lin-reg tests. Try to get all terms added.

**Comment by nniiicc** [comment]
Document tests - what assumptions are you working from, and what hypotheses are being pursued? 
@lindseysschwartz - We need a pre-registration filed before this work continues.

**Comment by thin-lizard** [comment]
Yes. I have a working draft [here](https://docs.google.com/document/d/16b5xpRgpdtRaLRq32_1VvWQ_ufTxT7hHCdB7Skb8N38/edit#) and can draft out the "analysis plan" section by Wed

**Comment by evamaxfield** [comment]
https://doi.org/10.1002/ajim.23295 and https://docs.google.com/document/d/1wgiNEhmQ6WxCWwFixqU8qhK_V4aDrdkvGgKch_S6Gko/edit#
