### ISSUE TITLE
Speakerbox JOSS Paper Review from Nic

### ISSUE THREAD

**Issue by evamaxfield** [PugetSoundClinic-PIT/ProjectTracking#29]
@nniiicc please review JOSS paper draft so we can prep for submission

Link: https://github.com/CouncilDataProject/speakerbox/blob/main/paper/paper.md

**Comment by nniiicc** [comment]
Just pushed suggested edits. 
I left two in-line comments:
- Request to make some clearer connections between related work 
- Use of splits vs subsets 

A few other places I asked a clarifying question, and suggested citing the previous CDP Joss paper. 
 
After these are cleared up please submit - looks good! 👌

**Comment by evamaxfield** [comment]
Nic has reviewed. Back to me for changes and then submit.

**Comment by evamaxfield** [comment]
Submitted / will be placed in pre-review in the next two-ish days.


![Image](https://user-images.githubusercontent.com/17132317/197672191-24c741e3-d257-4dd0-b038-039f284d2a59.png)
