### ISSUE TITLE
Lab Practice Talk

### ISSUE THREAD

**Issue by evamaxfield** [PugetSoundClinic-PIT/ProjectTracking#30]
Update talk to resolve Bill's comments:

* Sahn plot -- call out points on plot (looking for policy signatures)
* Annotate the plot with the budget proposal days (suggestive towards future work)
* whats the throughline.
* give the one slide intro into "this is a one slide intro to civics"

Schedule and give practice talk to lab

**Comment by nniiicc** [comment]
How about 
- Check in with co-author before you present?
