### ISSUE TITLE
Capstone / Research Database Posting Review from Nic + Actual Submit

### ISSUE THREAD

**Issue by evamaxfield** [PugetSoundClinic-PIT/ProjectTracking#31]
Get review from @nniiicc and post the final thing to the Capstone submission and the research database

Link: https://docs.google.com/document/d/1MB4j8O4Czz2_7MRr1Wvq5NkW7dGRybB4rGdGisZiG1w/edit?usp=sharing

**Comment by nniiicc** [comment]
Done
