### ISSUE TITLE
Figure Out Starting Point for Angel

### ISSUE THREAD

**Issue by evamaxfield** [PugetSoundClinic-PIT/ProjectTracking#32]
All of her paperwork is in it seems. Idk if it needs to go through @nniiicc or not?

**Comment by nniiicc** [comment]
I don't know what you are asking

**Comment by evamaxfield** [comment]
Angel submitted all of her paperwork to the Undergrad UW iSchool Admin to do a research capstone with CDP for tagging special interest groups.

I am just trying to keep things moving. This is the only thing on the [Undergrad research capstone details page](https://ischool.uw.edu/capstone/students/informatics) that is next: 

> The Informatics chair will approve or decline research proposals to ensure that the proposed work constitutes a significant research experience.

Which isn't either of us but I am wondering when Angel can actually start working on the project. Just trying to plan like "Hey Angel, with your submission of the paperwork, we are waiting on the undergrad chair, but we should be able to start on Nov. 3. Want to stop by the datalab and we can chat about first steps?"

That type of deal. The question is really: "what is the timeline for the final administrative stuff so I can coordinate with her."

**Comment by nniiicc** [comment]
Got it - you can coordinate with her now (or when it is convenient). The approval from INFO chair is pro-forma - they will send me an email at some point and I will confirm.
